registration_form = "https://accounts.ukr.net/registration"
travels_demo = "https://phptravels.com/demo"
test_auto_practice = "http://testautomationpractice.blogspot.com/"
frames_page = "https://seleniumhq.github.io/selenium/docs/api/java/index.html"
worlds_countries = "https://www.countries-ofthe-world.com/flags-of-the-world.html"
opensource = "https://opensource-demo.orangehrmlive.com"
demo_guru_context = "http://demo.guru99.com/test/simple_context_menu.html"
demo_guru_drag = "http://demo.guru99.com/test/drag_drop.html"
