registration_form = "https://accounts.ukr.net/registration"
travels_demo = "https://phptravels.com/demo"
test_auto_practice = "http://testautomationpractice.blogspot.com/"
frames_page = "https://seleniumhq.github.io/selenium/docs/api/java/index.html"
worlds_countries = "https://www.countries-ofthe-world.com/flags-of-the-world.html"
